# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 01:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bf_road_arc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_co', models.CharField(max_length=10)),
                ('feature_ty', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=80)),
                ('width', models.FloatField()),
                ('source', models.CharField(max_length=6)),
                ('capture_da', models.DateField()),
                ('dispositio', models.FloatField()),
                ('disposit_1', models.CharField(max_length=6)),
                ('bf_id', models.FloatField()),
                ('shape_stle', models.FloatField()),
                ('shape_st_1', models.FloatField()),
                ('shape_st_2', models.FloatField()),
                ('objectid', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4269)),
            ],
        ),
    ]
