# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='canvec_style_def',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=250)),
                ('geom_outcolor', models.CharField(max_length=80)),
                ('geom_width', models.FloatField()),
                ('geom_symbol', models.CharField(max_length=80)),
                ('polyfill_symbol', models.CharField(max_length=80)),
                ('polyfill_fillcolor', models.CharField(max_length=80)),
                ('polyfill_angle', models.FloatField()),
                ('polyfill_hatchgap', models.FloatField()),
                ('polyfill_hatchthick', models.IntegerField()),
                ('label_font', models.CharField(max_length=80)),
                ('label_fillcolor', models.CharField(max_length=80)),
                ('label_outcolor', models.CharField(max_length=80)),
                ('label_height', models.IntegerField()),
            ],
        ),
    ]
