# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobase', '0002_canvec_style_def'),
    ]

    operations = [
        migrations.CreateModel(
            name='j_style_altalis20k',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altalis20k', models.CharField(max_length=250)),
                ('nrcan_shortname', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='canvec_style_def',
            name='id',
        ),
        migrations.AlterField(
            model_name='canvec_style_def',
            name='shortname',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
