# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 21:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown location', max_length=50)),
                ('mpoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
