# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geodata', '0003_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
