# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_auto_20161209_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
