# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0007_auto_20161209_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpslocation',
            name='device_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geodata.Device'),
            preserve_default=False,
        ),
    ]
